### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by jlqzzz** [Liz66666/SIENet#1]
Dear authors, I'm very interested in your work. May I ask when you plan to release the code? Thanks!

**Comment by liuhuaijjin** [comment]
I also expect the author to release the code. I added PCN into the pointrCNN, but the running accuracy became worse. I think that sampling the point cloud after completing the false point cloud will affect the border correction

**Comment by Liz66666** [comment]
Hi @liuhuaijjin and @jlqzzz, thanks for your interest in our work. The code of SIENet has been released, we hope it will be helpful for your research.
