### ISSUE TITLE
Can you provide related configurations for pedestrians and cyclists?

### ISSUE THREAD

**Issue by jlqzzz** [Liz66666/SIENet#4]
I noticed that the method in your paper can detect cars, pedestrians and cyclists, but the current code only contains the relevant configuration of car class.

Can you provide related configurations for pedestrians and cyclists?

**Comment by Liz66666** [comment]
Hi @jlqzzz , the current code only supports the detection of car categories. However, I am struggling with some new works recently. If you need them urgently, you can obtain the incomplete point clouds and corresponding GT by simply sampling objects of pedestrians and cyclists from the KITTI dataset. Then refer to #5 to train the completion network.

Hope this helps you.
