### ISSUE TITLE
Can you provide the pre-training code and training data of spatial shape prediction network?

### ISSUE THREAD

**Issue by jlqzzz** [Liz66666/SIENet#5]
As described in your paper, spatial shape prediction networks need to be pre-trained under specially constructed dataset. However, this part is missing in the current code.

Can you provide the pre-training code and training data of spatial shape prediction network?

**Comment by Liz66666** [comment]
Hi @jlqzzz , thanks for your interest in our work. The official implementation of PCN (https://github.com/wentaoyuan/pcn) has provided detailed codes for dataset construction and model training. Thus it is advised to refer to that project for pre-training the completion network.

**Comment by jlqzzz** [comment]
> Hi @jlqzzz , thanks for your interest in our work. The official implementation of PCN (https://github.com/wentaoyuan/pcn) has provided detailed codes for dataset construction and model training. Thus it is advised to refer to that project for pre-training the completion network.

In my opinion, the spatial shape prediction module is a key part of your paper. The pre-training of spatial shape prediction network depends very much on the training data of cars, pedestrians and cyclists specially constructed by you.

In addition, since you have provided the corresponding pre training model, I believe you have organized the relevant pre-training data and code.

I hope you can upload this part of the corresponding training data and code, which may not take too much time for you, but it may waste a lot of unnecessary energy for others to reproduce your results.

Thank you again for your great pioneering work!  With regard to the above questions, I hope I can get your further help.

**Comment by Liz66666** [comment]
> > Hi @jlqzzz , thanks for your interest in our work. The official implementation of PCN (https://github.com/wentaoyuan/pcn) has provided detailed codes for dataset construction and model training. Thus it is advised to refer to that project for pre-training the completion network.
> 
> In my opinion, the spatial shape prediction module is a key part of your paper. The pre-training of spatial shape prediction network depends very much on the training data of cars, pedestrians and cyclists specially constructed by you.
> 
> In addition, since you have provided the corresponding pre training model, I believe you have organized the relevant pre-training data and code.
> 
> I hope you can upload this part of the corresponding training data and code, which may not take too much time for you, but it may waste a lot of unnecessary energy for others to reproduce your results.
> 
> Thank you again for your great pioneering work! With regard to the above questions, I hope I can get your further help.

Actually, the pre-training code has not been organized well. I am currently working on some new projects, which are time-consuming for me. I might make the pre-training code available, but it still needs some time.

**Comment by jlqzzz** [comment]
> > > Hi @jlqzzz , thanks for your interest in our work. The official implementation of PCN (https://github.com/wentaoyuan/pcn) has provided detailed codes for dataset construction and model training. Thus it is advised to refer to that project for pre-training the completion network.
> > 
> > 
> > In my opinion, the spatial shape prediction module is a key part of your paper. The pre-training of spatial shape prediction network depends very much on the training data of cars, pedestrians and cyclists specially constructed by you.
> > In addition, since you have provided the corresponding pre training model, I believe you have organized the relevant pre-training data and code.
> > I hope you can upload this part of the corresponding training data and code, which may not take too much time for you, but it may waste a lot of unnecessary energy for others to reproduce your results.
> > Thank you again for your great pioneering work! With regard to the above questions, I hope I can get your further help.
> 
> Actually, the pre-training code has not been organized well. I am currently working on some new projects, which are time-consuming for me. I might make the pre-training code available, but it still needs some time.

OK, I see. Thank you for your prompt reply. We look forward to the early release of the pre-training code and data of the spatial shape prediction network!
